import { useState } from 'react';
import { motion } from 'framer-motion';
import { Download, FileText, Calendar, User, Activity, CheckCircle, AlertCircle, Award, Shield } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Separator } from '@/components/ui/separator';
import { Badge } from '@/components/ui/badge';

export function PDFReportPage() {
  const [isGenerating, setIsGenerating] = useState(false);
  
  // Mock data for demonstration
  const reportData = {
    patient: {
      name: 'John Doe',
      age: 45,
      gender: 'Male',
      id: 'PT-2025-001'
    },
    date: new Date().toLocaleDateString(),
    xrayResult: {
      diagnosis: 'Normal',
      confidence: 95,
      description: 'No signs of pneumonia or tuberculosis detected. Chest appears normal.',
      status: 'Normal'
    },
    coughResult: {
      classification: 'Normal Cough',
      confidence: 92,
      characteristics: ['Dry', 'Normal frequency', 'Short duration'],
      status: 'Normal'
    },
    chatbotSummary: [
      'Patient inquired about preventive measures for respiratory health',
      'Provided guidance on maintaining good respiratory hygiene',
      'Recommended regular health checkups'
    ],
    recommendations: [
      'Continue regular health checkups',
      'Maintain good respiratory hygiene',
      'Stay hydrated and get adequate rest',
      'Monitor any changes in symptoms'
    ]
  };

  const handleDownloadReport = async () => {
    setIsGenerating(true);
    
    // Simulate PDF generation
    await new Promise(resolve => setTimeout(resolve, 2000));
    
    // Create a simple PDF download simulation
    const element = document.createElement('a');
    const file = new Blob([`
SwasthSetu Health Report
=====================

Patient Information:
- Name: ${reportData.patient.name}
- Age: ${reportData.patient.age}
- Gender: ${reportData.patient.gender}
- Patient ID: ${reportData.patient.id}
- Date: ${reportData.date}

X-ray Analysis:
- Diagnosis: ${reportData.xrayResult.diagnosis}
- Confidence: ${reportData.xrayResult.confidence}%
- Description: ${reportData.xrayResult.description}

Cough Analysis:
- Classification: ${reportData.coughResult.classification}
- Confidence: ${reportData.coughResult.confidence}%
- Characteristics: ${reportData.coughResult.characteristics.join(', ')}

Recommendations:
${reportData.recommendations.map(rec => `- ${rec}`).join('\n')}

---
Generated by SwasthSetu AI System
This report is for informational purposes only and should not replace professional medical advice.
    `], { type: 'text/plain' });
    
    element.href = URL.createObjectURL(file);
    element.download = `SwasthSetu_Report_${reportData.patient.name.replace(' ', '_')}_${new Date().toISOString().split('T')[0]}.txt`;
    document.body.appendChild(element);
    element.click();
    document.body.removeChild(element);
    
    setIsGenerating(false);
  };

  return (
    <div className="min-h-screen py-20">
      <div className="max-w-4xl mx-auto px-4 sm:px-6 lg:px-8">
        {/* Floating Report Elements */}
        <div className="absolute inset-0 overflow-hidden pointer-events-none">
          <motion.div
            className="absolute top-32 right-16 text-blue-200"
            animate={{
              y: [0, -20, 0],
              rotate: [0, 15, 0],
            }}
            transition={{
              duration: 4,
              repeat: Infinity,
              ease: "easeInOut"
            }}
          >
            <Award className="w-8 h-8" />
          </motion.div>
          
          <motion.div
            className="absolute bottom-40 left-12 text-green-200"
            animate={{
              y: [0, 25, 0],
              x: [0, 15, 0],
            }}
            transition={{
              duration: 5,
              repeat: Infinity,
              ease: "easeInOut",
              delay: 1
            }}
          >
            <Shield className="w-6 h-6" />
          </motion.div>
        </div>
        
        <motion.div
          initial={{ opacity: 0, y: 30 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 1, ease: "easeOut" }}
          className="text-center mb-12"
        >
          <motion.div
            initial={{ scale: 0 }}
            animate={{ scale: 1 }}
            transition={{ duration: 0.6, delay: 0.3 }}
            className="inline-flex items-center px-4 py-2 bg-emerald-100 rounded-full text-emerald-700 text-sm font-medium mb-6"
          >
            <FileText className="w-4 h-4 mr-2" />
            Comprehensive Health Report
          </motion.div>
          
          <h1 className="text-4xl lg:text-5xl font-bold text-gray-900 mb-6">
            Health Report
          </h1>
          <motion.p
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ duration: 0.8, delay: 0.5 }}
            className="text-xl text-gray-600 max-w-2xl mx-auto"
          >
            Comprehensive summary of your diagnostic results and health recommendations.
          </motion.p>
        </motion.div>

        <div className="space-y-8">
          {/* Patient Information */}
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 1, delay: 0.2 }}
          >
            <Card className="bg-white/90 backdrop-blur-sm shadow-xl border-0">
              <CardHeader>
                <CardTitle className="flex items-center">
                  <motion.div
                    animate={{ scale: [1, 1.1, 1] }}
                    transition={{ duration: 2, repeat: Infinity }}
                  >
                    <User className="w-5 h-5 mr-2 text-blue-600" />
                  </motion.div>
                  Patient Information
                </CardTitle>
              </CardHeader>
              <CardContent>
                <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-4">
                  {[
                    { label: 'Name', value: reportData.patient.name },
                    { label: 'Age', value: reportData.patient.age },
                    { label: 'Gender', value: reportData.patient.gender },
                    { label: 'Report Date', value: reportData.date }
                  ].map((item, index) => (
                    <motion.div
                      key={item.label}
                      initial={{ opacity: 0, y: 20 }}
                      animate={{ opacity: 1, y: 0 }}
                      transition={{ delay: 0.1 * index }}
                      whileHover={{ scale: 1.02 }}
                      className="p-3 bg-gray-50 rounded-lg"
                    >
                    <p className="text-sm font-medium text-gray-500">Name</p>
                    <p className="text-lg font-semibold">{reportData.patient.name}</p>
                    </motion.div>
                  ))}
                </div>
              </CardContent>
            </Card>
          </motion.div>

          {/* Diagnostic Results */}
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 1, delay: 0.4 }}
          >
            <Card className="bg-white/90 backdrop-blur-sm shadow-xl border-0">
              <CardHeader>
                <CardTitle className="flex items-center">
                  <motion.div
                    animate={{ rotate: [0, 360] }}
                    transition={{ duration: 3, repeat: Infinity, ease: "linear" }}
                  >
                    <Activity className="w-5 h-5 mr-2 text-blue-600" />
                  </motion.div>
                  Diagnostic Results
                </CardTitle>
                <CardDescription>
                  AI-powered analysis results from X-ray and cough assessment
                </CardDescription>
              </CardHeader>
              <CardContent className="space-y-6">
                {/* X-ray Results */}
                <div className="space-y-3">
                  <div className="flex items-center justify-between">
                    <motion.h4
                      initial={{ opacity: 0, x: -20 }}
                      animate={{ opacity: 1, x: 0 }}
                      transition={{ delay: 0.2 }}
                      className="font-semibold text-lg"
                    >
                      X-ray Analysis
                    </motion.h4>
                    <motion.div
                      initial={{ scale: 0 }}
                      animate={{ scale: 1 }}
                      transition={{ delay: 0.4 }}
                    >
                      <Badge variant={reportData.xrayResult.status === 'Normal' ? 'default' : 'destructive'}>
                      {reportData.xrayResult.status === 'Normal' ? (
                        <CheckCircle className="w-3 h-3 mr-1" />
                      ) : (
                        <AlertCircle className="w-3 h-3 mr-1" />
                      )}
                      {reportData.xrayResult.status}
                      </Badge>
                    </motion.div>
                  </div>
                  <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: 0.3 }}
                    whileHover={{ scale: 1.01 }}
                    className="grid grid-cols-1 md:grid-cols-2 gap-4 p-4 bg-gray-50 rounded-xl shadow-inner"
                  >
                    <div>
                      <p className="text-sm font-medium text-gray-500">Diagnosis</p>
                      <p className="font-semibold">{reportData.xrayResult.diagnosis}</p>
                    </div>
                    <div>
                      <p className="text-sm font-medium text-gray-500">Confidence</p>
                      <p className="font-semibold">{reportData.xrayResult.confidence}%</p>
                    </div>
                    <div className="md:col-span-2">
                      <p className="text-sm font-medium text-gray-500">Description</p>
                      <p className="text-sm text-gray-700">{reportData.xrayResult.description}</p>
                    </div>
                  </motion.div>
                </div>

                <Separator />

                {/* Cough Results */}
                <div className="space-y-3">
                  <div className="flex items-center justify-between">
                    <motion.h4
                      initial={{ opacity: 0, x: -20 }}
                      animate={{ opacity: 1, x: 0 }}
                      transition={{ delay: 0.5 }}
                      className="font-semibold text-lg"
                    >
                      Cough Analysis
                    </motion.h4>
                    <motion.div
                      initial={{ scale: 0 }}
                      animate={{ scale: 1 }}
                      transition={{ delay: 0.7 }}
                    >
                      <Badge variant={reportData.coughResult.status === 'Normal' ? 'default' : 'destructive'}>
                      {reportData.coughResult.status === 'Normal' ? (
                        <CheckCircle className="w-3 h-3 mr-1" />
                      ) : (
                        <AlertCircle className="w-3 h-3 mr-1" />
                      )}
                      {reportData.coughResult.status}
                      </Badge>
                    </motion.div>
                  </div>
                  <motion.div
                    initial={{ opacity: 0, y: 20 }}
                    animate={{ opacity: 1, y: 0 }}
                    transition={{ delay: 0.6 }}
                    whileHover={{ scale: 1.01 }}
                    className="grid grid-cols-1 md:grid-cols-2 gap-4 p-4 bg-gray-50 rounded-xl shadow-inner"
                  >
                    <div>
                      <p className="text-sm font-medium text-gray-500">Classification</p>
                      <p className="font-semibold">{reportData.coughResult.classification}</p>
                    </div>
                    <div>
                      <p className="text-sm font-medium text-gray-500">Confidence</p>
                      <p className="font-semibold">{reportData.coughResult.confidence}%</p>
                    </div>
                    <div className="md:col-span-2">
                      <p className="text-sm font-medium text-gray-500">Characteristics</p>
                      <div className="flex flex-wrap gap-2 mt-1">
                        {reportData.coughResult.characteristics.map((char, index) => (
                          <motion.div
                            key={index}
                            initial={{ scale: 0 }}
                            animate={{ scale: 1 }}
                            transition={{ delay: 0.1 * index }}
                          >
                            <Badge variant="outline">{char}</Badge>
                          </motion.div>
                        ))}
                      </div>
                    </div>
                  </motion.div>
                </div>
              </CardContent>
            </Card>
          </motion.div>

          {/* Chatbot Summary */}
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 1, delay: 0.6 }}
          >
            <Card className="bg-white/90 backdrop-blur-sm shadow-xl border-0">
              <CardHeader>
                <CardTitle>Consultation Summary</CardTitle>
                <CardDescription>
                  Key points from your AI assistant consultation
                </CardDescription>
              </CardHeader>
              <CardContent>
                <ul className="space-y-2">
                  {reportData.chatbotSummary.map((item, index) => (
                    <motion.li
                      key={index}
                      initial={{ opacity: 0, x: -20 }}
                      animate={{ opacity: 1, x: 0 }}
                      transition={{ delay: 0.1 * index }}
                      whileHover={{ x: 5 }}
                      className="flex items-start"
                    >
                      <div className="w-2 h-2 bg-blue-600 rounded-full mt-2 mr-3 flex-shrink-0"></div>
                      <span className="text-sm text-gray-700">{item}</span>
                    </motion.li>
                  ))}
                </ul>
              </CardContent>
            </Card>
          </motion.div>

          {/* Recommendations */}
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 1, delay: 0.8 }}
          >
            <Card className="bg-white/90 backdrop-blur-sm shadow-xl border-0">
              <CardHeader>
                <CardTitle>Recommendations</CardTitle>
                <CardDescription>
                  Personalized health recommendations based on your results
                </CardDescription>
              </CardHeader>
              <CardContent>
                <div className="space-y-3">
                  {reportData.recommendations.map((recommendation, index) => (
                    <motion.div
                      key={index}
                      initial={{ opacity: 0, y: 20 }}
                      animate={{ opacity: 1, y: 0 }}
                      transition={{ delay: 0.1 * index }}
                      whileHover={{ scale: 1.02, x: 5 }}
                      className="flex items-start p-3 bg-blue-50 rounded-xl shadow-sm"
                    >
                      <CheckCircle className="w-5 h-5 text-blue-600 mt-0.5 mr-3 flex-shrink-0" />
                      <span className="text-sm text-blue-900">{recommendation}</span>
                    </motion.div>
                  ))}
                </div>
              </CardContent>
            </Card>
          </motion.div>

          {/* Download Section */}
          <motion.div
            initial={{ opacity: 0, y: 30 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ duration: 1, delay: 1.0 }}
            className="text-center"
          >
            <Card className="bg-gradient-to-br from-blue-50 to-indigo-50 border-0 shadow-xl">
              <CardContent className="pt-6">
                <div className="space-y-4">
                  <motion.div
                    animate={{ 
                      y: [0, -10, 0],
                      rotate: [0, 5, 0]
                    }}
                    transition={{ duration: 3, repeat: Infinity }}
                  >
                    <FileText className="w-16 h-16 text-blue-400 mx-auto" />
                  </motion.div>
                  <div>
                    <h3 className="text-lg font-semibold mb-2">Download Your Report</h3>
                    <p className="text-gray-600 mb-6">
                      Get a comprehensive PDF report with all your diagnostic results and recommendations.
                    </p>
                  </div>
                  <motion.div
                    whileHover={{ scale: 1.05 }}
                    whileTap={{ scale: 0.95 }}
                  >
                    <Button
                    onClick={handleDownloadReport}
                    disabled={isGenerating}
                    size="lg"
                    className="w-full sm:w-auto bg-gradient-to-r from-emerald-600 to-green-600 hover:from-emerald-700 hover:to-green-700 shadow-lg hover:shadow-xl transition-all duration-300"
                    >
                    {isGenerating ? (
                      <>
                        <motion.div
                          animate={{ rotate: 360 }}
                          transition={{ duration: 1, repeat: Infinity, ease: "linear" }}
                          className="rounded-full h-4 w-4 border-b-2 border-white mr-2"
                        />
                        Generating Report...
                      </>
                    ) : (
                      <>
                        <Download className="w-4 h-4 mr-2" />
                        Download PDF Report
                      </>
                    )}
                    </Button>
                  </motion.div>
                </div>
              </CardContent>
            </Card>
          </motion.div>
        </div>

        {/* Disclaimer */}
        <motion.div
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ duration: 0.8, delay: 1.2 }}
          className="mt-8 p-4 bg-yellow-50 border border-yellow-200 rounded-lg"
        >
          <p className="text-sm text-yellow-800 text-center">
            <strong>Medical Disclaimer:</strong> This report is generated by AI and is for informational purposes only. 
            It should not be used as a substitute for professional medical advice, diagnosis, or treatment. 
            Always consult with qualified healthcare providers for medical decisions.
          </p>
        </motion.div>
      </div>
    </div>
  );
}